import { dir } from 'i18next'; // Ensure dir returns 'ltr' or 'rtl' based on the language.
import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Noto_Sans_JP, Noto_Sans_KR } from 'next/font/google';
import Preload from './preload';
import './globals.css';
import { fallbackLng } from './i18n/settings';

const notoSansJP = Noto_Sans_JP({
  variable: '--font-noto-sans-jp',
  subsets: ['latin'],
});

const notoSansKR = Noto_Sans_KR({
  variable: '--font-noto-sans-kr',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
  params?: Promise<{ lng?: string }>;
}

export default async function RootLayout({ children, params }: RootLayoutProps) {
  // Await params if present
  const resolvedParams = params ? await params : undefined;
  const currentLng = resolvedParams?.lng || fallbackLng;

  console.log('RootLayout - currentLng:', currentLng, 'dir:', dir(currentLng));

  return (
    <html lang={currentLng} dir={dir(currentLng)}>
      <head />
      <body className={`${notoSansJP.variable} ${notoSansKR.variable} antialiased`}>
        <Preload>{children}</Preload>
      </body>
    </html>
  );
}